orders/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path("orders", views.AddGoodToBacket.as_view(), name="add_to_baskeet"),
    path("add_product/<int:pk>", views.add_to_basket, name="add_to_basket"),
    path('basket', views.show_basket, name="basket"),
    path("remove/<int:pk>", views.remove_from_basket, name="remove_form_basket"),
    path("submit", views.submit_order, name='submit'),
    path("", views.Index.as_view(), name="index")
]

pizza/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("orders.urls")),
    path("accounts/login/", auth_views.LoginView.as_view()),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL )

orders/models.py
from django.contrib.auth.models import User
from django.db import models


class Cathegory(models.Model):
    name = models.CharField(max_length=100, blank=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    cathegory = models.ForeignKey(Cathegory, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    large = models.BooleanField(default=True)
    price = models.FloatField()
    price1 = models.FloatField(null=True, blank=True)

    def __str__(self):
        return f"{self.cathegory.name}-{self.name}"


class Addons(models.Model):
    cathegory = models.ForeignKey(Cathegory, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.cathegory.name}- add-ons:{self.name}"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, blank=True, null=True)
    data = models.DateTimeField(auto_now=True)
    done = models.BooleanField(default=False)
    checked = models.BooleanField(default=False)
    tel = models.CharField(max_length=15, blank=True, null=True, default=None)
    cost = models.FloatField(verbose_name="total sum", default=0)

    def __str__(self):
        return f"{self.tel or self.user.first_name}-{self.data.date()}"+\
               f"-{self.cost}$-  send-{self.done}"


class OderItems(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    large = models.BooleanField(default=False)
    toping1 = models.ForeignKey(Addons, on_delete=models.DO_NOTHING, default=None, null=True, blank=True,
                                related_name="first_topping")
    toping2 = models.ForeignKey(Addons, on_delete=models.DO_NOTHING, default=None, null=True, blank=True,
                                related_name="second_topping")
    toping3 = models.ForeignKey(Addons, on_delete=models.DO_NOTHING, default=None, null=True, blank=True,
                                related_name="therd_topping")
    price = models.FloatField()

    def __str__(self):
        return f"{self.product.name}-"

orders/views.py
from builtins import print
# from pprint import pprint
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.views.generic import *
from django import forms
from .models import *


# Create your views here.

class GoodsCookiesMixin:
    def get_context_data(self, *, object_list=None, **kwards):
        # self.request.session.clear()
        context = super().get_context_data(object_list=None, **kwards)
        context['basket_items'] = len(self.request.session.get("basket", []))
        context['menu'] = True
        # pprint(context)
        print("basket:", self.request.session.get('basket', []))
        return context


class Index(GoodsCookiesMixin, ListView):
    model = Cathegory
    template_name = 'orders/index.html'


class AddToBasketForm(forms.Form):
    product = forms.CharField(max_length=100)

    def is_valid(self):
        return super().is_valid()


class AddToBasketModelForm(forms.Form):
    def __init__(self, cathegory, *args, **kwargs):
        super(AddToBasketModelForm, self).__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.objects.all()

    class Meta:
        model = OderItems
        exclude = []


class AddGoodToBacket(FormView):
    form_class = AddToBasketModelForm
    # form_class = AddToBasketForm
    template_name = 'orders/product_form.html'
    success_url = "index"

    def form_valid(self, form):
        print(self.request.POST)
        return super().form_valid(form)


def add_to_basket(request, pk):
    cathegory = get_object_or_404(Cathegory, pk=pk)
    # print(request.session.keys())
    if request.method == "POST":
        # print(request.POST)
        form = dict(request.POST)
        # print(form, form.get('addon'))
        request.session['basket'] = request.session.get('basket', []) + \
                                    [[int(form['cathegory'][0]),
                                      int(form['product'][0]),
                                      [int(i) for i in form.get('addon', [])]
                                      ]]
        return redirect("index")
    return render(request, "orders/product_form.html", context={'cathegory': cathegory})


# @login_required
def show_basket(request):
    content = {}
    basket = []
    print(request.session.get('basket', []))
    for category, product, addon in request.session.get('basket', []):
        cathegory_name = Cathegory.objects.get(pk=category).name
        prod = Product.objects.get(pk=product)
        product_name = prod.name
        price = prod.price
        addons = [Addons.objects.get(pk=item).name for item in addon]
        basket.append({"cathegory": cathegory_name, "product": product_name, 'addons': addons, 'price': price})
    return render(request, "orders/basket.html", context={"basket": basket})


def remove_from_basket(request, pk):
    request.session.modified = True
    request.session['basket'].pop(pk)
    return redirect("basket")


def submit_order(request):
    print("I'm in the submit order ")
    print(request.method)
    if request.method == "POST":
        form = dict(request.POST)
        # print(form['tel'])
        if request.user.is_authenticated or form['tel']:
            if not len(request.session.get('basket', [])):
                print("Basket ampty")
                return redirect("index")
            # save order into database
            print(form)
            if request.user.is_authenticated:
                order = Order(user=User.objects.get(pk=request.user.id))
            else:
                order = Order(tel=form['tel'])
            order.save()
            print("Save order ")

            for category, product, adds in request.session['basket']:
                topping1 = None
                topping2 = None
                topping3 = None

                for n, add in enumerate(adds):
                    if n == 0:
                        topping1 = Addons.objects.get(pk=add)
                    if n == 1:
                        topping1 = Addons.objects.get(pk=add)
                    if n == 2:
                        topping2 = Addons.objects.get(pk=add)
                    order_item = OderItems(order=order,
                                           product=Product.objects.get(pk=product),
                                           large=1,
                                           toping1=topping1,
                                           toping2=topping2,
                                           toping3=topping3,
                                           price=Product.objects.get(pk=product).price)
                order_item.save()
                print("Save order - item ")
    del request.session['basket']
    request.session.modified = True

    return redirect("index")

orders/templates/orders/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>{% block title %}

    {% endblock %}</title>
</head>
<body>
    <h3 >
        <div >
            <a href="{% url "index" %}"> <img width="20%" height="10%" src="{% static "orders/index.jpeg" %}" alt="home"></a>
        </div>

        {% if menu %}
            <div style="text-align: right">
            <a href="{% url "basket" %}"> Basket -- {{  basket_items }} products.</a>

            </div>
        {% endif %}
    </h3>

{% block content %}

{% endblock %}

</body>
</html>

orders/templates/orders/basket.html
{% extends "orders/base.html" %}

{% block title %}
    Basket
{% endblock %}

{% block content %}

    <h2> You have chacked: </h2>
    {% for item in basket %}
        <div> {{ forloop.counter }}.
            {{ item.cathegory }} - {{ item.product }}
            {% if item.addons %} with [
                {% for addon in item.addons %}
                    {{ addon }},
                {% endfor %}
            ]
            {% endif %}

            {{ item.price }} $
            <a href="{% url "remove_form_basket"  forloop.counter0%} "> Remove </a>
        </div>

    {% endfor %}
    <form action="{% url 'submit' %}" method="post">
        {% csrf_token %}
        {% if not user.is_authenticated %}
        <input type="tel" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" name="tel" required>
        <span class="note">Format: 123-456-7890</span>
        {% endif %}
        <p>
            <input type="submit" value="Замовити">
        </p>
    </form>

{% endblock %}

orders/templates/orders/index.html
{% extends "orders/base.html" %}

{% block title %}
 Menu
{% endblock %}

{% block content %}
{% for cathegory in cathegory_list %}
    <h2><a href="{% url "add_to_basket" cathegory.id%}">
        {{ cathegory.name }}

    </a>
    </h2>
    <ul>
    {% if cathegory.product_set.all.first.large%}
    <p>
        <b>small,     large</b>
    </p>
    {% endif %}
    {% for product in cathegory.product_set.all %}
        <li> {{ product.name }} - {{ product.price }}
            {% if product.large %}
                {{ product.price1 }}
            {% endif %}
        
        </li>
    {% endfor %}

    {% if cathegory.addons_set.first %}
        <h2>Addons:</h2>
    {% endif %}
    {% for addon in cathegory.addons_set.all %}
        <p>
            {{ addon.name }}
        </p>
    {% endfor %}
    </ul>
<hr>
{% endfor %}


{% endblock %}

orders/templates/orders/product_form.html
{% extends "orders/base.html" %}

{% block title %}
    Add to Dish to basket
{% endblock %}

{% block content %}

    <h2>{{ cathegory.name }}</h2>
    <ul>
    {% if cathegory.product_set.all.first.large%}
    <p>
        <b>small,     large</b>
    </p>
    {% endif %}
    {% for product in cathegory.product_set.all %}
        <li> {{ product.name }} - {{ product.price }}
            {% if product.large %}
                {{ product.price1 }}
            {% endif %}

        </li>
    {% endfor %}

        <form action="" method="post">

            {% if cathegory.product_set.first.large %}
                <label>
                    <H4>Large
                        <input type="checkbox" name="large" value='1'>
                    </H4>
                </label>
            {% endif %}
            <input type="hidden" name="cathegory" value="{{ cathegory.id }}">

            {% if cathegory.addons_set.all %}
                <input type="hidden" name="product" value="{{ cathegory.product_set.first.id }}">

            {% endif %}

            {% if cathegory.addons_set.all  %}
                {% for addons in cathegory.addons_set.all %}
                    <p>

                        <label> {{ addons.name }}
                            <input type="checkbox"
                                   name="addon"
                                   value="{{ addons.id}}">
                        </label>
                    </p>


                {% endfor %}
            {% else %}
                {% for product in cathegory.product_set.all %}
                    </p>
                    <label>
                        <input type="radio" name="product" value={{ product.id }}>
                        {{ product.name }}
                        </label>
                    <p>

                {% endfor %}

            {% endif %}

{#        {{ form.as_p }}#}
        {% csrf_token %}
        <input type="submit" value="Замовити">
    </form>
{% endblock %}